parameters:
    shop_settings:
        sales:
            start: 27/11/2020_00:00
            end: 29/11/2020_23:59
    stripe_secret_key:     '%env(resolve:STRIPE_SECRET_KEY)%'
    stripe_secret_webhook: '%env(resolve:STRIPE_SECRET_WEBHOOK)%'
    stripe_public_key:     '%env(resolve:STRIPE_PUBLIC_KEY)%'