liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: 'img/cache'
    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/public'

    driver: "gd"

    filter_sets:
        icon:
            quality: 75
            filters:
                thumbnail: { size: [33,40], mode: outbound}
        thumb:
            quality: 75
            filters:
                thumbnail: { size: [251,329], mode: outbound}
                background: { size: [255,333], position: center, color: '#000000'}
        large:
            quality: 75
            filters:
                thumbnail: { size: [600,750], mode: outbound}