liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: 'img/cache'
    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/%env(PUBLIC_PATH)%'

    driver: "gd"

    filter_sets:
        icon:
            quality: 75
            filters:
                thumbnail: { size: [33,40], mode: outbound}
        620x350:
            quality: 75
            filters:
                thumbnail: { size: [620,350], mode: outbound}
        square:
            quality: 75
            filters:
                thumbnail: { size: [200,200], mode: outbound}
        item_thumb:
            quality: 75
            filters:
                thumbnail: { size: [115,115], mode: outbound}
        item_big:
            quality: 75
            filters:
                thumbnail: { size: [550,720], mode: outbound}
        item_related:
            quality: 75
            filters:
                thumbnail: { size: [516,688], mode: outbound}
        thumb:
            quality: 75
            filters:
                thumbnail: { size: [251,329], mode: outbound}
                background: { size: [255,333], position: center}
        small:
            quality: 75
            filters:
                thumbnail: { size: [ 200,300 ], mode: outbound }
        large:
            quality: 75
            filters:
                thumbnail: { size: [600,750], mode: outbound}
        og:
            quality: 75
            filters:
                thumbnail: { size: [1200,630], mode: outbound}