parameters:
    shop_settings:
        sales:
            start: 27/11/2020_00:00
            end: 29/11/2020_23:59
    stripe_secret_key:     '%env(STRIPE_SECRET_KEY_TEST)%'
    stripe_secret_webhook: '%env(STRIPE_SECRET_WEBHOOK_TEST)%'
    stripe_public_key:     '%env(STRIPE_PUBLIC_KEY_TEST)%'
    paypal_secret_key:     '%env(PAYPAL_SECRET_KEY_TEST)%'
    paypal_public_key:     '%env(PAYPAL_PUBLIC_KEY_TEST)%'